import type { Metadata } from "next";
import { Roboto, Philosopher } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["cyrillic"],
  weight: ["400","500","700"]
});

const philosopher = Philosopher({
  variable: "--font-philosopher",
  subsets: ["cyrillic"],
  weight: ["400","700"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${philosopher.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
